### PR TITLE
Added all around great guy

### PR DESCRIPTION
**Pull request by ghost**
It seemed like the title did not have an ending. So this change seems
like it ends it rather than just abruptly ending it.

### CODE REVIEW

**Comment by Brantoe** [comment]
I don't know about this choice, it might destabilize the infrastructure of our project. I think we need more buckets before attempting something like this again. Everyone knows that .net framework is determined by 8 digits of ones and zeros and uhhh.... you know... Just get your ducks in a row peter.

**Comment by ghost** [comment]
I can either focus on my duck aligning capabilities or my abilities to add thermal energy to oceans.  Pick one @Brantoe !

**Comment by Brantoe** [comment]
Both have equally important implications when considering the field of biology... you know genes, alleles, protein carbohydrates, you know.

**Comment by ghost** [comment]
Yes I do!  You completely live up to your title!

**Pull request merged**
